AllCops:
  Include:
  - '**/Rakefile'
  - '**/config.ru'
  Exclude:
  - 'packaging/**/*'
  - 'vendor/bundle/**/*'
  - 'bin/*'
  - 'spec/*_helper.rb'
  - 'db/**/*.rb'
  - 'db/schema.rb'
  - 'config/**/*'
  - 'script/**/*'
  - 'tmp/**/*'
  - !ruby/regexp /old_and_unused\.rb$/
  UseCache: false
  TargetRubyVersion: 2.5

Rails:
  Enabled: true

StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/Delegate:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
